services:
#    la_user.example:
#        class: La\UserBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    la_user.friendshipService:
        class: La\UserBundle\Services\userService
        arguments: [@doctrine.orm.entity_manager, userId ,newFriendId]

