<?php

namespace La\UserBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use La\UserBundle\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	/**
	* find actual friends
	* @param User user
	* @return arrayCollection User
	*/
	public function findFriends(User $user){
		return $this->createQueryBuilder('u')
			->join('u.friendships', 'f')
		    ->where('f.user2 = :user', 'f.status = 2')
		    ->setParameter(':user', $user)
		    ->getQuery()
		    ->getResult();
	}

	/**
	* find friends not validate
	* @param User user
	* @return arrayCollection User
	*/
	public function findFriendsWaitingForAnswer(User $user){
		return $this->createQueryBuilder('u')
			->join('u.friendships', 'f')
		    ->where('f.user2 = :user', 'f.status = 0')
		    ->setParameter(':user', $user)
		    ->getQuery()
		    ->getResult();
	}

	/**
	* find waiting friendship
	* @param User user
	* @return arrayCollection User
	*/
	public function findFriendsRequestToAnswer(User $user){
		return $this->createQueryBuilder('u')
			->join('u.friendships', 'f')
		    ->where('f.user2 = :user', 'f.status = 1')
		    ->setParameter(':user', $user)
		    ->getQuery()
		    ->getResult();
	}
}