la_user:
    resource: "@LaUserBundle/Resources/config/routing.yml"
    prefix:   /users

la_app:
    resource: "@LaAppBundle/Resources/config/routing.yml"
    prefix:   /

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app:
    resource: @AppBundle/Controller/
    type:     annotation

#REST 
rest_users : 
    type : rest 
    resource : La\UserBundle\Controller\UsersApiController
    prefix : /api

rest_messages : 
    type : rest 
    resource : La\AppBundle\Controller\MessagesApiController
    prefix : /api
